### PR TITLE
[TS] LPP-46273 > LPS-161050 Keep track on the fieldset's fields on rendering

### PR DESCRIPTION
**Pull request by ces-hongvo**
Hi,
This is a PR for fixing the issue in the ticket https://issues.liferay.com/browse/LPP-46273
Please review this and leave your comments.
Thank you.

### CODE REVIEW

**Comment by ces-hongvo** [comment]
ci:test:bundle

**Comment by rodrigopaulino** [comment]
This repo is not used. Please send this to @liferay-forms. Thx!

**Comment by rodrigopaulino** [comment]
ci:close

**Comment by ces-hongvo** [comment]
Hi @rodrigopaulino 
Yes, I have forwarded it to https://github.com/liferay-forms/liferay-portal/pull/1925.
Thank you.

**Pull request closed without merging**
